import json
import os
from pathlib import Path

from dotenv import load_dotenv
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_groq import ChatGroq
from pydantic import BaseModel

from models import (
    FinalIncidentReport,
    IncidentInput,
    SpecialistFinding,
    ToolObservation,
    TriageDecision,
)
from tools import (
    check_billing_account,
    check_optical_signal,
    check_pppoe_service,
)


PROJECT_DIR = Path(__file__).resolve().parent
load_dotenv(PROJECT_DIR / ".env")

DEFAULT_MODEL = "openai/gpt-oss-20b"


class FinalDecisionDraft(BaseModel):
    """Small structured response generated by the final LLM."""

    probable_root_cause: str
    decision: str
    action_plan: list[str]
    assigned_team: str
    confidence: str


def get_llm() -> ChatGroq:
    """Create the Groq language model used by the agents."""

    if not os.getenv("GROQ_API_KEY"):
        raise RuntimeError(
            "GROQ_API_KEY is missing. Add it to the local .env file."
        )

    model_name = os.getenv("GROQ_MODEL", DEFAULT_MODEL)

    return ChatGroq(
        model=model_name,
        temperature=0,
        timeout=90,
        max_retries=5,
    )


def format_incident(incident: IncidentInput) -> str:
    """Convert an incident into formatted JSON."""

    return incident.model_dump_json(indent=2)


def unique_items(items: list[str]) -> list[str]:
    """Remove duplicate strings while preserving their order."""

    return list(dict.fromkeys(item for item in items if item))


def deterministic_triage(
    incident: IncidentInput,
) -> TriageDecision:
    """Create a safe triage result without requiring the API."""

    description = incident.description.lower()
    assigned_agents: list[str] = []
    reasons: list[str] = []

    fiber_keywords = (
        "fiber",
        "los",
        "pon",
        "onu",
        "optical",
        "signal",
        "splice",
        "connector",
    )

    network_keywords = (
        "pppoe",
        "mikrotik",
        "router",
        "internet",
        "network",
        "wan",
        "dns",
        "offline",
    )

    billing_keywords = (
        "payment",
        "paid",
        "unpaid",
        "billing",
        "balance",
        "account",
        "disabled",
    )

    fiber_evidence = (
        incident.onu_los_status == "red"
        or incident.onu_pon_status == "offline"
        or incident.rx_power_dbm is not None
        or any(word in description for word in fiber_keywords)
    )

    network_evidence = (
        incident.pppoe_status != "unknown"
        or any(word in description for word in network_keywords)
    )

    billing_evidence = (
        incident.payment_status != "unknown"
        or incident.account_status != "unknown"
        or any(word in description for word in billing_keywords)
    )

    if fiber_evidence:
        assigned_agents.append("fiber_agent")
        reasons.append(
            "The incident contains ONU, LOS, PON, optical-signal "
            "or fiber evidence."
        )

    if network_evidence:
        assigned_agents.append("network_agent")
        reasons.append(
            "The incident contains PPPoE, router or network evidence."
        )

    if billing_evidence:
        assigned_agents.append("billing_agent")
        reasons.append(
            "The incident contains payment or account-status evidence."
        )

    if len(assigned_agents) > 1:
        category = "mixed"
    elif assigned_agents == ["fiber_agent"]:
        category = "fiber"
    elif assigned_agents == ["network_agent"]:
        category = "network"
    elif assigned_agents == ["billing_agent"]:
        category = "billing"
    else:
        category = "unknown"

    broad_outage = any(
        phrase in description
        for phrase in (
            "all customers",
            "all users",
            "multiple customers",
            "multiple users",
            "area outage",
            "complete outage",
        )
    )

    critical_optical_signal = (
        incident.rx_power_dbm is not None
        and incident.rx_power_dbm < -27
    )

    if broad_outage:
        priority = "critical"
    elif (
        incident.onu_los_status == "red"
        or critical_optical_signal
    ):
        priority = "high"
    elif (
        incident.pppoe_status == "inactive"
        or incident.account_status == "disabled"
        or incident.payment_status in {"unpaid", "partial"}
    ):
        priority = "medium"
    else:
        priority = "low"

    return TriageDecision(
        category=category,
        priority=priority,
        assigned_agents=assigned_agents,
        reason=" ".join(reasons) or (
            "The supplied incident does not contain enough evidence "
            "to select a specialist."
        ),
        requires_human_escalation=broad_outage,
    )


def coordinator_agent(
    incident: IncidentInput,
) -> TriageDecision:
    """Use the LLM for triage with a deterministic fallback."""

    system_prompt = """
You are the coordinator of a fictional ISP multi-agent incident
response system.

Analyze the submitted incident and assign all relevant specialists.

Available specialists:

- fiber_agent: ONU, LOS, PON, RX power, fiber and optical faults
- network_agent: PPPoE, MikroTik, router, WAN and service faults
- billing_agent: payments, balances, account enablement and suspension

Rules:

1. Assign every specialist needed for a reliable diagnosis.
2. Use category "mixed" when multiple areas are involved.
3. A red LOS or critical optical signal is high priority.
4. A broad outage or safety risk is critical priority.
5. A paid-but-disabled account requires billing investigation.
6. Use only the supplied fictional incident data.
""".strip()

    try:
        structured_llm = get_llm().with_structured_output(
            TriageDecision,
            method="json_schema",
        )

        return structured_llm.invoke(
            [
                SystemMessage(content=system_prompt),
                HumanMessage(
                    content=(
                        "Triage this fictional ISP incident:\n\n"
                        f"{format_incident(incident)}"
                    )
                ),
            ]
        )
    except Exception:
        return deterministic_triage(incident)


def fiber_agent(
    incident: IncidentInput,
) -> SpecialistFinding:
    """Run the optical diagnostic tool and return its finding."""

    observation_data = check_optical_signal.invoke(
        {
            "onu_pon_status": incident.onu_pon_status,
            "onu_los_status": incident.onu_los_status,
            "rx_power_dbm": incident.rx_power_dbm,
        }
    )

    observation = ToolObservation(**observation_data)

    evidence = [
        f"ONU PON status: {incident.onu_pon_status}",
        f"ONU LOS status: {incident.onu_los_status}",
        f"Tool status: {observation.status}",
    ]

    if incident.rx_power_dbm is not None:
        evidence.append(
            f"RX optical power: {incident.rx_power_dbm:.1f} dBm"
        )

    recommended_actions = [
        observation.recommended_check,
        "Record the result of every physical fiber and optical test.",
    ]

    if observation.status == "fault":
        diagnosis = observation.summary
        confidence = "high"
        requires_escalation = True
    elif observation.status == "warning":
        diagnosis = observation.summary
        confidence = "medium"
        requires_escalation = True
    elif observation.status == "normal":
        diagnosis = (
            "The supplied optical evidence does not show a confirmed "
            "fiber fault."
        )
        confidence = "high"
        requires_escalation = False
    else:
        diagnosis = (
            "The optical condition cannot be confirmed from the "
            "supplied information."
        )
        confidence = "low"
        requires_escalation = False

    return SpecialistFinding(
        agent="fiber_agent",
        diagnosis=diagnosis,
        evidence=evidence,
        recommended_actions=recommended_actions,
        confidence=confidence,
        requires_escalation=requires_escalation,
        tool_observations=[observation],
    )


def network_agent(
    incident: IncidentInput,
) -> SpecialistFinding:
    """Run the PPPoE diagnostic tool and return its finding."""

    observation_data = check_pppoe_service.invoke(
        {
            "pppoe_status": incident.pppoe_status,
            "account_status": incident.account_status,
        }
    )

    observation = ToolObservation(**observation_data)

    evidence = [
        f"PPPoE status: {incident.pppoe_status}",
        f"Account status: {incident.account_status}",
        f"Tool status: {observation.status}",
    ]

    recommended_actions = [
        observation.recommended_check,
        (
            "After authorization is confirmed, verify PPPoE "
            "credentials, service profile and router WAN settings."
        ),
        (
            "Record the MikroTik session result without exposing "
            "private credentials."
        ),
    ]

    if observation.status == "fault":
        diagnosis = observation.summary
        confidence = "high"
        requires_escalation = True
    elif observation.status == "warning":
        diagnosis = observation.summary
        confidence = "medium"
        requires_escalation = True
    elif observation.status == "normal":
        diagnosis = (
            "The PPPoE session is active, so further checks should "
            "focus on LAN, Wi-Fi, DNS or the customer device."
        )
        confidence = "high"
        requires_escalation = False
    else:
        diagnosis = (
            "The network condition cannot be confirmed because the "
            "PPPoE state is unknown."
        )
        confidence = "low"
        requires_escalation = False

    return SpecialistFinding(
        agent="network_agent",
        diagnosis=diagnosis,
        evidence=evidence,
        recommended_actions=recommended_actions,
        confidence=confidence,
        requires_escalation=requires_escalation,
        tool_observations=[observation],
    )


def billing_agent(
    incident: IncidentInput,
) -> SpecialistFinding:
    """Run the billing diagnostic tool and return its finding."""

    observation_data = check_billing_account.invoke(
        {
            "payment_status": incident.payment_status,
            "account_status": incident.account_status,
        }
    )

    observation = ToolObservation(**observation_data)

    evidence = [
        f"Payment status: {incident.payment_status}",
        f"Account status: {incident.account_status}",
        f"Tool status: {observation.status}",
    ]

    recommended_actions = [
        observation.recommended_check,
        (
            "Document the billing verification before any approved "
            "account-status change."
        ),
    ]

    if observation.status == "fault":
        diagnosis = observation.summary
        confidence = "high"
        requires_escalation = True
    elif observation.status == "warning":
        diagnosis = observation.summary
        confidence = "medium"
        requires_escalation = True
    elif observation.status == "normal":
        diagnosis = (
            "The supplied billing information does not show a "
            "payment or account activation fault."
        )
        confidence = "high"
        requires_escalation = False
    else:
        diagnosis = (
            "The billing condition cannot be confirmed from the "
            "supplied information."
        )
        confidence = "low"
        requires_escalation = False

    return SpecialistFinding(
        agent="billing_agent",
        diagnosis=diagnosis,
        evidence=evidence,
        recommended_actions=recommended_actions,
        confidence=confidence,
        requires_escalation=requires_escalation,
        tool_observations=[observation],
    )


SPECIALIST_AGENTS = {
    "fiber_agent": fiber_agent,
    "network_agent": network_agent,
    "billing_agent": billing_agent,
}


def run_assigned_specialist(
    agent_name: str,
    incident: IncidentInput,
) -> SpecialistFinding:
    """Run one specialist selected by the coordinator."""

    agent_function = SPECIALIST_AGENTS.get(agent_name)

    if agent_function is None:
        raise ValueError(
            f"Unknown specialist agent: {agent_name}"
        )

    return agent_function(incident)


def deterministic_final_draft(
    findings: list[SpecialistFinding],
) -> FinalDecisionDraft:
    """Create a reliable final decision without requiring the API."""

    fault_summaries: list[str] = []
    action_plan: list[str] = []
    teams: list[str] = []

    team_names = {
        "fiber_agent": "Fiber Team",
        "network_agent": "Network Team",
        "billing_agent": "Billing Team",
    }

    for finding in findings:
        if finding.tool_observations:
            observation = finding.tool_observations[0]

            if observation.status in {"fault", "warning"}:
                fault_summaries.append(observation.summary)

        action_plan.extend(finding.recommended_actions)

        team_name = team_names.get(finding.agent)

        if team_name:
            teams.append(team_name)

    action_plan = unique_items(action_plan)
    teams = unique_items(teams)

    if fault_summaries:
        probable_root_cause = " ".join(
            unique_items(fault_summaries)
        )
        decision = (
            "The incident requires coordinated specialist action. "
            "Complete the verified checks in order and restore service "
            "only after the physical, network and billing conditions "
            "are confirmed."
        )
    else:
        probable_root_cause = (
            "No confirmed fault was established from the supplied "
            "incident evidence."
        )
        decision = (
            "Collect the missing diagnostic information before making "
            "a service-impacting change."
        )

    if not action_plan:
        action_plan = [
            "Collect additional fiber, PPPoE and billing evidence.",
        ]

    confidence_values = {
        finding.confidence
        for finding in findings
    }

    if "high" in confidence_values:
        confidence = "high"
    elif "medium" in confidence_values:
        confidence = "medium"
    else:
        confidence = "low"

    return FinalDecisionDraft(
        probable_root_cause=probable_root_cause,
        decision=decision,
        action_plan=action_plan,
        assigned_team=", ".join(teams) or "Support Team",
        confidence=confidence,
    )


def final_decision_agent(
    incident: IncidentInput,
    triage: TriageDecision,
    findings: list[SpecialistFinding],
) -> FinalIncidentReport:
    """Combine all findings using the LLM with a safe fallback."""

    findings_json = json.dumps(
        [
            finding.model_dump()
            for finding in findings
        ],
        indent=2,
    )

    system_prompt = """
You are the final decision agent in a fictional ISP multi-agent
incident response system.

Combine the coordinator triage and specialist findings into one clear
operational decision.

Rules:

1. Use only the supplied evidence.
2. Do not invent completed tests, payments or repairs.
3. Prioritize direct diagnostic-tool evidence.
4. Put urgent and safety-related actions first.
5. Do not expose private credentials.
6. Account restoration requires approved billing verification.
7. Return a concise ordered action plan.
""".strip()

    try:
        structured_llm = get_llm().with_structured_output(
            FinalDecisionDraft,
            method="json_schema",
        )

        draft = structured_llm.invoke(
            [
                SystemMessage(content=system_prompt),
                HumanMessage(
                    content=(
                        "Incident:\n\n"
                        f"{format_incident(incident)}\n\n"
                        "Coordinator triage:\n\n"
                        f"{triage.model_dump_json(indent=2)}\n\n"
                        "Specialist findings:\n\n"
                        f"{findings_json}"
                    )
                ),
            ]
        )

        confidence = draft.confidence.lower()

        if confidence not in {"high", "medium", "low"}:
            confidence = "medium"

    except Exception:
        draft = deterministic_final_draft(findings)
        confidence = draft.confidence

    requires_escalation = (
        triage.requires_human_escalation
        or any(
            finding.requires_escalation
            for finding in findings
        )
    )

    return FinalIncidentReport(
        incident_id=incident.incident_id,
        category=triage.category,
        priority=triage.priority,
        probable_root_cause=draft.probable_root_cause,
        decision=draft.decision,
        action_plan=draft.action_plan,
        assigned_team=draft.assigned_team,
        confidence=confidence,
        requires_human_escalation=requires_escalation,
        specialist_findings=findings,
        workflow_path=[],
    )